### ISSUE TITLE
Is this project dead for good?

### ISSUE THREAD

**Issue by mojo2012** [vsilaev/tascalate-async-await#4]
Hi,

this projects sounds awesome. But no updated in over 2 years? Are there any plans to revive it?

**Comment by vsilaev** [comment]
Hello,

Thank you for your interest in this project.
Good news -- I don't consider this project myself as "dead" and I plan to re-start development in Aug/Sep.
Bad news -- there are a lot of things to do to make it work with Java 9+.

The list is:
1. Refactor `Tascalate JavaFlow` to use new naming for modules and packages - it's very unintuitive currently to have a difference between Java 9 module names and packages (due to legacy code reasons)
2. Finalize `Tascalate Instrument` project to provide a version-independent variant of Java Agents and class loading
3. Refactor `Tascalate Async/Await` itself to create a multi-version project with Java 9 support (plus use single-shot continujations plus use version-agnostic agents and class loading).

Unfortunately,  I'm bad of attracting contributors to the aforementioned projects so all the work will be done solely by me in a free time, so no fast results can be promised.

**Comment by mojo2012** [comment]
Thanks for the fast response. I will keep an eye on the project.
Do you have project loom on the radar? It doesn't entirely satisfy the same need as this project but there might be some similarities (byte code rewriting maybe?).

**Comment by vsilaev** [comment]
@mojo2012 -- development is restarted. I skipped step [1] from the list above -- just updated `Tascalate JavaFlow` to support Java 6-18. `Tascalate Instrument` is completed. And `Async / Await` is in active development mode now.

**Comment by mojo2012** [comment]
Do you have any release date in mind? I'd love to integrate this is my work :-D

**Comment by vsilaev** [comment]
I plan to release before/on Aug 8 at least smth. that works for major cases (no edge cases, though).
Currently I'm able to run examples after Maven enhancements, need to fix JavaAgent part.
So if you plan to integrate this project into your work then it will be a test bench for the release )

**Comment by mojo2012** [comment]
I can't await this :-) Thanks for the cool work, btw! I wished I had more time for stuff like this too :-)

**Comment by vipcxj** [comment]
@mojo2012 
I write a async-await project too, And the first release is published, and I will fix any bug in several days.

**Comment by mojo2012** [comment]
@vipcxj  that really looks promising. Can't wait to try it out.

**Comment by vsilaev** [comment]
@mojo2012 @vipcxj 
Sorry for the delay, stucked with my primary work assignments (

The remaining part is instrumentation agent, however, if you are doing compile-time weaving you can start updating your code right away -- clone project sources and run Maven build (with JDK 9+):

```
mvn clean install -P release
```

This way you will get the new version  locally and can verify it.

**Comment by mojo2012** [comment]
Wouldn't it be nice for you two to join your work? It seems like both libraries share the same idea, why not combine your knowhow?

**Comment by vsilaev** [comment]
@mojo2012 
Unrealistic. Very different implementation approaches -- I just have looked at the JAsync briefly.

**Comment by mojo2012** [comment]
The main pom.xml contains an old unpublished SNAPSHOT of `maven-javadoc-plugin`. You could update it. Furthermore I can't build a release branch without a proper gnupg setup. Building without a profile seems to work though.

**Comment by vsilaev** [comment]
> at org.apache.commons.javaflow.providers.asm5.Asm5ClassTransformer.transform
Wow! ASM 5... It's very outdated... Not sure what version of the async-await + javaflow you are using...

**Comment by vsilaev** [comment]
Version 1,1,0 released, please check https://github.com/vsilaev/tascalate-async-await/releases/tag/1.1.0
Full support for Java 9 - 17 is added.
